### ISSUE TITLE
Project: Killer.App

### ISSUE THREAD

**Issue by ascasson** [EugTech/open-eugene-projects-and-programs#1]
**Description**: An open source, mobile enabled and fully adaptable game that uses Alternate Reality Gaming methods linked with elements of True Crime fandom and an escape room ethos. 

**Type of project**: Open Source Software : Release your code using an OSS License, Open Data : You have APIs or raw data you would like accessible to more people

**Needs**: Looking for more collaborators

**State of development**: It's a working project, but not open yet

**Project owner**: Joseph M, @eugeniusestech

**Comment by markdav-is** [comment]
Please provide the following that we can use for marketing your project, talk, workshop or other programming.  You can drang-and-drop images here.  

- [ ] your github handle (so we can link to you and use your profile picture)
- [ ] Link to your project online or a slide deck or whatever you;d like to link to.
- [ ] Any special A/V needs beyond an HDMI port

**Comment by CannonKim** [comment]
Joseph contacted me to let me know that they will not be able to participate in the festival.
